name: example
description: An example project to show the usage of translate_ref_generator.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  translate_ref:
    git:
      url: https://github.com/haroldadmin/translate_ref
      ref: 0.0.2

dev_dependencies:
  build_runner: ^1.10.4
  translate_ref_generator:
    path: '../'
  pedantic: ^1.9.0
