builders:
  translate_ref_generator:
    import: 'package:translate_ref_generator/translate_ref_generator.dart'
    builder_factories: ['translationReferenceBuilder']
    build_extensions:
      .lang.json:
        - .lang.dart
    build_to: source
    auto_apply: dependents
