name: translate_ref_generator
description: A generator for translation string keys in Dart
version: 0.0.2

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  build: ^1.5.0
  path: ^1.7.0
  file: ^5.2.1
  source_gen: ^0.9.8
  translate_ref:
    git: https://github.com/haroldadmin/translate_ref

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.10.4
  build_test: ^1.3.0
  pedantic: ^1.9.0
  test: ^1.14.4
